title: "Grant Stagg"
email: "grastagg@gmail.com"
description: >-
  PhD student specializing in autonomous UAV safety in adversarial environments.
  I develop algorithms for probabilistic engagement zone modeling, uncertainty-aware path planning,
  and real-time inference using machine learning and control theory.

url: "https://grantstagg.github.io"
baseurl: ""  # Leave this empty for user/organization site

# Author information
author:
  name   : "Grant Stagg"
  avatar : "/assets/images/avatar.png"
  bio    : "PhD student | UAV autonomy | Probabilistic safety modeling"
  location: "Provo, UT"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:grastagg@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/grant-stagg"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0009-0006-9899-8551"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/grantstagg"

# Theme
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

# Defaults for collections
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Navigation bar items (set in _data/navigation.yml, not here)


